# Generated by Django 5.2 on 2025-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collect',
            name='collected_amount',
        ),
        migrations.AddField(
            model_name='collect',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Собранная сумма'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='contributors_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество жертвователей'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цель'),
        ),
    ]
